### ISSUE TITLE
Make the classes stronger by looping over the breakpoints array from the json file

### ISSUE THREAD

**Issue by rob-bar** [Crosscheck/Jacket#32]
in _grid.scss

``` scss
$grids: (1, 2, 3, 4, 5, 6);
@each $i in $grids {
  .grid-#{$i} {
    &.mobile {
      @include media(med(mobile)) {
        @include grid($i);
      }
    }

    &.tablet {
      @include media(med(tablet)) {
        @include grid($i);
      }
    }

    &.desktop {
      @include media(med(desktop)) {
        @include grid($i);
      }
    }
  }
}
```

to something like this:

``` scss
$grids: (1, 2, 3, 4, 5, 6);
@each $i in $grids {
  .grid-#{$i} {
    //for that loops over the keys in the breakpoints sass-map
  }
}
```
