### ISSUE TITLE
Investigate if we need to add html font size:100%

### ISSUE THREAD

**Issue by rob-bar** [Crosscheck/Jacket#41]
We should include:
Because when we do this, it is easyer to meet customers requirements, 
when they want to resize all the fonts and rhythms.

``` css
html {
  font-size: 100%;
}
```
