### ISSUE TITLE
Remove duplicate old base font sizes.

### ISSUE THREAD

**Issue by rob-bar** [Crosscheck/Jacket#42]
``` scss
/// Rembase variable
//// @group Typography
//// @type Value
$rembase: 16;

/// Base font size in px
//// @group Typography
//// @type Value
$base-font-size: 15px;

/// Base line height in px
//// @group Typography
//// @type Value
$base-line-height: 25px;
```

the $base-font-size is the only one that should be used.
Als this should be set to 16px.

$rembase: 16; should be removed
and 

``` scss
/// Set the font-size with a px fallback
//// @group Typography
/// @param {value} $size [none] - font-size
/// @param {unit} $unit [rem] - unit used for font-size
@mixin font-size($size, $unit: rem) {
  @if $rem-with-px-fallback == true {
    font-size: $size + px;
  }

  font-size: $size / $rembase + $unit;
}

/// Set the line-height with a px fallback
//// @group Typography
/// @param {value} $line-height [none] - line-height
/// @param {unit} $unit [rem] - unit used for line-height
@mixin line-height($line-height, $unit: rem) {
  @if $rem-with-px-fallback == true {
    line-height: $line-height + px;
  }

  line-height: $line-height / $rembase + $unit;
}
```

Should use $base-font-size instead of rembase.
